### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by DrPariah** [KorGgenT/cdda-item-creator#13]
Hello, KorGgenT, and I'm sorry to bother you! I was looking for CDDA related utilities online, this came up. Looks interesting, but it doesn't seem to have any instructions for compiling or anything. How would you get it working?
(I know it's not up to date, but I'm mostly playing with E Stable or not too long after that release experimental, all pre-Nested stuff, so it would still have utility)

**Comment by KorGgenT** [comment]
there are .exe files in the releases tab - but if you already have visual studio then you can clone and run it from the solution. if you're wanting to compile it i assume you want to help get it a few more features or something? or if you just want to use it, just download the executables from the releases tab.

**Comment by DrPariah** [comment]
Ah, that's me being unfamiliar with Git. Mostly looking for using it, I don't have any coding ability. Thank you for explaining!
